### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by ErikEJ** [madskristensen/SqlFormatter#2]
Great extension. 

I suggest renaming to SQL Formatter rather than Sql Formatter

Re SSMS support, assume you are aware that your extension id must be on a Allow list and the extension must be installed in Program Files. (See Sqlite Toolbox)

**Comment by erinstellato-ms** [comment]
@ErikEJ For an extension to work with SSMS it doesn't *have* to be installed in Program Files.

**Comment by ErikEJ** [comment]
Interesting. Where can it be installed??

**Comment by erinstellato-ms** [comment]
@ErikEJ Whoops, I was wrong.   My apologies - I was doing a lot of testing yesterday and I thought I was able to make it work with a different directory.  Nope.  Also, Mads is a PM in VS - we're in good hands here.

**Comment by ErikEJ** [comment]
Cool, I could never make SSMS 20 load my extension from anywhere else (SQLite Toolbox) - but it loads fine from Program Files.

**Comment by madskristensen** [comment]
Good idea renaming it. I always like the way `Sql` looked over `SQL`, even though I know it is wrong :)
